# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ugqZ1vTRgnZkTW6j5VRUpJnaw0pXRdr6
"""

import streamlit as st
import pandas as pd
import joblib

# Load saved model and scaler
model = joblib.load("budget_stress_model.pkl")
scaler = joblib.load("budget_stress_scaler.pkl")

# Risk level function
def risk_level(prob):
    if prob < 0.30:
        return "Low"
    elif prob < 0.70:
        return "Medium"
    else:
        return "High"

# Prediction function
def predict_financial_stress(monthly_income, financial_aid, housing, food, transportation,
                             books_supplies, entertainment, personal_care,
                             technology, health_wellness, miscellaneous):

    input_data = pd.DataFrame([{
        'monthly_income': monthly_income,
        'financial_aid': financial_aid,
        'housing': housing,
        'food': food,
        'transportation': transportation,
        'books_supplies': books_supplies,
        'entertainment': entertainment,
        'personal_care': personal_care,
        'technology': technology,
        'health_wellness': health_wellness,
        'miscellaneous': miscellaneous
    }])

    input_scaled = scaler.transform(input_data)
    stress_probability = model.predict_proba(input_scaled)[0][1]
    stress_prediction = model.predict(input_scaled)[0]

    return int(stress_prediction), float(stress_probability)

# App title
st.title("Budget Shock Simulator")
st.write("Estimate the likelihood of monthly financial stress based on your budget inputs.")

# User inputs
monthly_income = st.number_input("Monthly Income", min_value=0, value=1500)
financial_aid = st.number_input("Financial Aid", min_value=0, value=250)
housing = st.number_input("Housing", min_value=0, value=1000)
food = st.number_input("Food", min_value=0, value=250)
transportation = st.number_input("Transportation", min_value=0, value=120)
books_supplies = st.number_input("Books & Supplies", min_value=0, value=60)
entertainment = st.number_input("Entertainment", min_value=0, value=100)
personal_care = st.number_input("Personal Care", min_value=0, value=50)
technology = st.number_input("Technology", min_value=0, value=70)
health_wellness = st.number_input("Health & Wellness", min_value=0, value=60)
miscellaneous = st.number_input("Miscellaneous", min_value=0, value=90)

if st.button("Calculate Risk"):
    total_funds = monthly_income + financial_aid
    total_spending = (
        housing + food + transportation + books_supplies +
        entertainment + personal_care + technology +
        health_wellness + miscellaneous
    )
    leftover_money = total_funds - total_spending

    predicted_class, stress_probability = predict_financial_stress(
        monthly_income, financial_aid, housing, food, transportation,
        books_supplies, entertainment, personal_care,
        technology, health_wellness, miscellaneous
    )

    st.subheader("Results")
    st.write(f"**Total Funds:** ${total_funds:,.0f}")
    st.write(f"**Total Spending:** ${total_spending:,.0f}")
    st.write(f"**Leftover Money:** ${leftover_money:,.0f}")
    st.write(f"**Predicted Financial Stress Probability:** {stress_probability:.1%}")
    st.write(f"**Risk Level:** {risk_level(stress_probability)}")